apiVersion: apps/v1
kind: Deployment
metadata:
  name: competition-node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: competition-node-app
  template:
    metadata:
      labels:
        app: competition-node-app
    spec:
      containers:
      - name: competition-node-app
        image: fixed-node-app:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP_NAME: "TerminalBench-Competition"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  DUMMY_SECRET: "topsecret"

